config/routes.rb
Rails.application.routes.draw do

root to: 'recipes#index'
resources :users, only:[:new, :create, :show]
resources :recipes, only:[:new, :create, :show]
resources :cookeries, only:[:new, :create, :show]
resources :foods, only:[:new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookery.rb
class Cookery < ApplicationRecord

  has_many :recipes

  validates :name, presence: true

end

app/models/food.rb
class Food < ApplicationRecord

  has_many :recipes

  validates :name, presence: true

end

app/models/recipe.rb
class Recipe < ApplicationRecord

  belongs_to :cookery
  belongs_to :food

  validates :name, :people_portion,
            :preparation_time, :difficult, :ingredients,
            :steps, presence: true

  scope :most_recent, -> {order(id: :desc)}

  searchkick

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }

end

app/models/user.rb
class User < ApplicationRecord

  validates :name, :email, :encrypted_password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cookeries_controller.rb
class CookeriesController < ApplicationController

  def new
    @cookery = Cookery.new
  end

  def create
    @cookery = Cookery.new(cookery_params)
    if @cookery.save
      redirect_to @cookery
    else
      flash[:notice] = 'Dado inválido'
      render :new
    end
  end

  def show
    @cookery = Cookery.find(params[:id])
    @cookeries = Cookery.includes(:recipes).where(recipes: { cookery_id: @cookery })
  end

  private

  def cookery_params
    params.require(:cookery).permit(:name)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to @food
    else
      flash[:notice] = 'Dado inválido'
      render :new
    end
  end

  def show
    @food = Food.find(params[:id])
  end


  private

  def food_params
    params.require(:food).permit(:name)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.most_recent.limit(20)
    @cookeries = Cookery.all

    if params[:keywords].present?
     @allrecipes = Recipe.search params[:keywords], fields: [:name, :ingredients]
   end
  end

  def new
    @recipe = Recipe.new
    @cookeries = Cookery.all
    @foods = Food.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      flash[:notice] = 'Dado inválido'
      @foods = Food.all
      @cookeries = Cookery.all
      render :new
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end


  private

  def recipe_params
  params.require(:recipe).permit(:name, :cookery_id, :food_id, :people_portion,
                                 :preparation_time, :difficult, :ingredients,
                                 :steps, :picture)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if  @user.save
      redirect_to @user
    else
      flash[:notice] = 'Dado inválido'
      render :new
    end

    def show
      @user = User.find(params[:id])
    end

  end


  private

  def users_params
  params.require(:user).permit(:name, :email, :encrypted_password,
                              :administrator)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookeries/new.html.erb
<%= notice %>

<%= form_for @cookery do |f| %>

  <dl>
    <dt><%= f.label :name, 'Digite o nome da cozinha' %></dt>
    <dd><%= f.text_field :name %></dd>

    <dt><%= f.submit 'Cadastrar a cozinha' %></dt>
  </dl>

<% end %>

app/views/cookeries/show.html.erb
<dl>
  <dt>Cozinha <%= @cookery.name %></dt>

<% @cookeries.each do |cookery| %>

  <ul>
    <% cookery.recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe_path(recipe) %></li>
    <% end %>
  </ul>
<% end %>

</dl>

app/views/foods/new.html.erb
<%= notice %>

<%= form_for @food do |f| %>

  <dl>
    <dt><%= f.label :name, 'Digite o nome do tipo de comida' %></dt>
    <dd><%= f.text_field :name %></dd>

    <dt><%= f.submit 'Cadastrar o tipo de comida' %></dt>
  </dl>

<% end %>

app/views/foods/show.html.erb
<%= @food.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <a class="navbar-brand" href="http://localhost:3000/"><strong>Social</strong> Recipes</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form role="form" action="/">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Início', root_path %></li>
          <li><%= link_to 'Cadastrar receitas', new_recipe_path %></li>
          <li><%= link_to 'Cadastrar usuários', new_user_path %></li>
          <li><%= link_to 'Cadastrar cozinha', new_cookery_path %></li>
          <li><%= link_to 'Cadastrar tipo de comida', new_food_path %></li>
          <li><input type="text" placeholder="Buscar" name="keywords"></li>
          <li><button type="submit" class="btn btn-primary btn-block">Submit</button></li>
      </form>

          </ul>
        </li>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <section class="recipes">
    <% if @allrecipes.present? %>
      <% @allrecipes.each do |recipe| %>
      <div class="col-md-12">
        <h1><%= recipe.name %></h1>
        <p><%= recipe.ingredients %></p>
          </div>
      <% end %>
    <% end %>
  </section>
</div>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row tipo-ultimas-receitas-favoritas">
     <div class="col-sm-3">
       <h3 id="tipo-de-comida">Tipo</h3>
        <p>Entrada</p>
        <p>Principal</p>
        <p>Sobremesa</p>
    </div>

    <div class="col-sm-4">
      <h3 id="ultimas-receitas">Últimas Receitas</h3>
        <div class="row ultimas-receitas">
            <div class="col-sm-4">
              <% @recipes.each do |recipe| %>
                <dt>
                  <dd><%= link_to recipe.name, recipe_path(recipe) %></dd>
                  <dd><%= recipe.food.name %></dd>
                  <dd><%= recipe.cookery.name %></dd>
                  <dd><%= recipe.difficult %></dd>
				  	<!--Início Teste -->
					<div class="panel-heading">
						<h4 class="panel-title">
							<a data-toggle="collapse" href="#collapse1"><%= recipe.name %></a>
						</h4>
					</div>
						<div id="collapse1" class="panel-collapse collapse">
						<div class="panel-body"><%= link_to recipe.name, recipe_path(recipe) %></div>
						<div class="panel-footer"><%= recipe.food.name %></div>
						<div class="panel-footer"><%= recipe.cookery.name %></div>
						<div class="panel-footer"><%= recipe.difficult %></div>
						
					</div>
					<!--Fim Teste-->
                </dt>
              <% end %>
           </div>

           <div class="col-sm-4">
             <p></p>

           </div>
        </div>

    </div>

     <div class="col-sm-4">
        <h3 id="favoritas-dos-usuarios">Favoritas dos Usuários</h3>
        <div class="row ultimas-receitas">
            <div class="col-sm-3">

           </div>

           <div class="col-sm-4">


           </div>
        </div>
    </div>
  </div>

  <div class="row cozinha">
     <div class="col-sm-3">
       <h3 id="cozinhas">Cozinha</h3>
         <% @cookeries.each do |cookery| %>
          <dt>
            <dd><%= link_to cookery.name, cookery_path(cookery) %></dd>
          </dt>
         <% end %>
    </div>

  </div
</div>

app/views/recipes/new.html.erb
<%= notice %>

<%= form_for @recipe, html: { multipart: true } do |f| %>
  <dl>
    <dt><%= f.label :name, 'Nome da receita' %></dt>
    <dd><%= f.text_field :name %><dd>

    <dt><%= f.label :picture, 'Insira uma imagem' %></dt>
    <dd><%= f.file_field :picture %><dd>

    <dt><%= f.label :cookery_id, 'Cozinha' %></dt>
    <dd><%= f.collection_select(:cookery_id, @cookeries, :id, :name) %></dd>


    <dt><%= f.label :food_id, 'Tipo de comida' %></dt>
    <dd><%= f.collection_select(:food_id, @foods, :id, :name) %></dd>

    <dt><%= f.label :people_portion, 'Quantas pessoas serve' %></dt>
    <dd><%= f.text_field :people_portion %></dd>

    <dt><%= f.label :preparation_time, 'Tempo de preparo' %></dt>
    <dd><%= f.text_field :preparation_time %></dd>

    <dt><%= f.label :difficult, 'Nível de dificuldade' %></dt>
    <dd><%= f.text_field :difficult %></dd>

    <dt><%= f.label :ingredients, 'Ingredientes' %></dt>
    <dd><%= f.text_field :ingredients %></dd>

    <dt><%= f.label :steps, 'Passo a passo' %></dt>
    <dd><%= f.text_field :steps %></dd>

    <br>

    <dt><%= f.submit 'Cadastrar receita' %></dt>

<% end %>

app/views/recipes/show.html.erb
<body>
 

<div class="jumbotron">
	<div class="container">
		<div class="col-lg-9">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title"><%= @recipe.name %></h3>
				</div><--panel-heading-->
				<div class="panel-body">
					<table class="table table-striped">
						<thead>
							<tr>
							<th>cookery.name</th>
							<th>food.name</th>
							<th>people_portion</th>
							<th>preparation_time</th>
							<th>difficult</th>				  
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><%= @recipe.cookery.name %></td>
								<td><%= @recipe.food.name %></td>
								<td><%= @recipe.people_portion %></td>
								<td><%= @recipe.preparation_time %></td>				
								<td><%= @recipe.difficult %></td>
							</tr>
							<tr>
								<td>Ingredientes:</td>
							</tr>
							<tr>
								<td class="img-responsive img-rounded-
center-block">						<h3 class="panel-title"><%= @recipe.ingredients %></h3>
								</td>
							</tr>
							<tr>
								<td>IMG	
									<%= image_tag @recipe.picture.url(:medium) %>
								</td>
							</tr>
							<tr>
								<td>
									<%= @recipe.steps %>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div><--panel panel-default-->
		</div><--col-lg-6 col-lg-offset-3-->
	</div><--container-->
</div><--jumbotron-->
</body>

app/views/users/new.html.erb
<%= notice %>

<%= form_for @user do |f| %>
  <dl>
    <dt><%= f.label :name, 'Nome do usuário' %></dt>
    <dd><%= f.text_field :name %><dd>

    <dt><%= f.label :email, 'Email' %></dt>
    <dd><%= f.text_field :email %></dd>

    <dt><%= f.label :encrypted_password, 'Senha' %></dt>
    <dd><%= f.password_field :encrypted_password %></dd>

    <dt><%= f.label :administrator, 'Administrador' %></dt>
    <dd><%= f.check_box :administrator %></dd>


    <br>

    <dt><%= f.submit 'Cadastrar usuário' %></dt>

<% end %>

app/views/users/show.html.erb
<dl>
  <dt><%= @user.name %></dt>
  <dt><%= @user.email %></dt>
  <dt><%= @user.encrypted_password %></dt>
  <dt><%= @user.administrator %></dt>
</dl>